{
 "title": "IoT Environment – Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "devices",
    "label": "Devices",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Température actuelle (°C)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "collection": "events",
     "queryLanguage": "json",
     "queryText": "[ { \"$match\": { \"deviceId\": \"$devices\", \"timestamp\": { \"$gt\": { \"$date\": { \"$numberLong\": \"$__from\" } }, \"$lt\": { \"$date\": { \"$numberLong\": \"$__to\" } } } } }, { \"$project\": { \"ts\": \"$timestamp\", \"value\": \"$value.t\" } }, { \"$sort\": { \"ts\": 1 } } ]"
    }
   ]
  },
  {
   "title": "Humidité actuelle (%)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "collection": "events",
     "queryLanguage": "json",
     "queryText": "[ { \"$match\": { \"deviceId\": \"$devices\",\"timestamp\": { \"$gt\": { \"$date\": { \"$numberLong\": \"$__from\" } }, \"$lt\": { \"$date\": { \"$numberLong\": \"$__to\" } } } } }, { \"$project\": { \"ts\": \"$timestamp\", \"value\": \"$value.h\" } }, { \"$sort\": { \"ts\": 1 } } ]"
    }
   ]
  },
  {
   "title": "Pression actuelle (hPa)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "collection": "events",
     "queryLanguage": "json",
     "queryText": "[{  \"$match\": { \"deviceId\": \"$devices\",\"timestamp\": {\"$gt\": { \"$date\": { \"$numberLong\": \"$__from\" } },\"$lt\": { \"$date\": { \"$numberLong\": \"$__to\" } } }  }},{ \"$project\": { \"ts\": \"$timestamp\", \"value\": \"$value.p\" } },{ \"$sort\": { \"ts\": 1 } }  ]"
    }
   ]
  },
  {
   "title": "Température (°C) – historique",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "collection": "events",
     "queryLanguage": "json",
     "queryText": "[ { \"$match\": { \"deviceId\": \"$devices\",\"timestamp\": { \"$gt\": { \"$date\": { \"$numberLong\": \"$__from\" } }, \"$lt\": { \"$date\": { \"$numberLong\": \"$__to\" } } } } }, { \"$project\": { \"ts\": \"$timestamp\", \"value\": \"$value.t\" } }, { \"$sort\": { \"ts\": 1 } } ]"
    }
   ]
  },
  {
   "title": "Humidité (%) – historique",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "collection": "events",
     "queryLanguage": "json",
     "queryText": "[ { \"$match\": { \"deviceId\": \"$devices\",\"timestamp\": { \"$gt\": { \"$date\": { \"$numberLong\": \"$__from\" } }, \"$lt\": { \"$date\": { \"$numberLong\": \"$__to\" } } } } }, { \"$project\": { \"ts\": \"$timestamp\", \"value\": \"$value.h\" } }, { \"$sort\": { \"ts\": 1 } } ]"
    }
   ]
  },
  {
   "title": "Pression (hPa) – historique",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "collection": "events",
     "queryLanguage": "json",
     "queryText": "[{  \"$match\": { \"deviceId\": \"$devices\",\"timestamp\": {\"$gt\": { \"$date\": { \"$numberLong\": \"$__from\" } },\"$lt\": { \"$date\": { \"$numberLong\": \"$__to\" } } }  }},{ \"$project\": { \"ts\": \"$timestamp\", \"value\": \"$value.p\" } },{ \"$sort\": { \"ts\": 1 } }  ]"
    }
   ]
  }
 ]
}